name: kublet
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  equatable: ^2.0.5
  intl: ^0.18.0
  dio: ^5.4.0
  autocomplete_textfield:
  dropdown_search: ^5.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSansRomanBold.ttf
          weight: 700
        - asset: assets/fonts/OpenSansRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/OpenSansRomanSemiBold.ttf
          weight: 600
    - family: Sen
      fonts:
        - asset: assets/fonts/SenExtraBold.ttf
          weight: 800
